# Generated by Django 3.1 on 2020-08-11 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_listed',
            new_name='date_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
