# Generated by Django 3.1 on 2020-08-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200811_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='seller',
            new_name='owner',
        ),
    ]
